name: Go

on:
  push:
    branches: [ "main", "dev", "coverage", "email-verification"]
  pull_request:
    branches: [ "main" ]
    
jobs:
  go-pipeline:
    uses: The-Psyducks/ci-template/.github/workflows/lint-test-coverage.yml@main

